"""alerts table

Revision ID: fe651cf3d0d7
Revises: dad1ea568222
Create Date: 2021-03-07 17:43:37.413397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe651cf3d0d7'
down_revision = 'dad1ea568222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('trailhead', sa.String(length=64), nullable=True),
    sa.Column('license_plate', sa.String(length=8), nullable=True),
    sa.Column('date_in', sa.Date(), nullable=True),
    sa.Column('date_out', sa.Date(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('delivery_time', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_date_in'), 'alert', ['date_in'], unique=False)
    op.create_index(op.f('ix_alert_date_out'), 'alert', ['date_out'], unique=False)
    op.create_index(op.f('ix_alert_delivery_time'), 'alert', ['delivery_time'], unique=False)
    op.create_index(op.f('ix_alert_license_plate'), 'alert', ['license_plate'], unique=False)
    op.create_index(op.f('ix_alert_timestamp'), 'alert', ['timestamp'], unique=False)
    op.create_index(op.f('ix_alert_title'), 'alert', ['title'], unique=False)
    op.create_index(op.f('ix_alert_trailhead'), 'alert', ['trailhead'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_trailhead'), table_name='alert')
    op.drop_index(op.f('ix_alert_title'), table_name='alert')
    op.drop_index(op.f('ix_alert_timestamp'), table_name='alert')
    op.drop_index(op.f('ix_alert_license_plate'), table_name='alert')
    op.drop_index(op.f('ix_alert_delivery_time'), table_name='alert')
    op.drop_index(op.f('ix_alert_date_out'), table_name='alert')
    op.drop_index(op.f('ix_alert_date_in'), table_name='alert')
    op.drop_table('alert')
    # ### end Alembic commands ###
